#!/bin/sh

if [ "$*" = "" ]; then
  >&2 echo "USAGE: $(basename "$0") ...TARGETS"
  >&2 echo "A small dt script to builds tvm"
  >&2 echo "TARGETS:"
  >&2 echo "  build   build tvm"
fi

while [ "$*" != "" ]; do
  if [ "$1" = "build" ]; then
    go build -v -x -o tvm src/main.go
  else
    >&2 echo "I don't know how to \"$1\""
  fi
  shift
done
